### ISSUE TITLE
[Update] Azure Classic service modules works with Powershell version 5.1

### ISSUE THREAD

**Issue by SauravB-MS** [Azure/azure-docs-powershell#2473]
[Enter feedback here]

Please update doc informing that the Azure Classic Module should be installed with Powershell version 5.1, not above. 
Powershell version 6 and above are built on .net core and AD authentication fails with the below error, when attempting add-AzureAccount

As Cloud service IaaS is approching deprecation timeline, it's expected that this doc will be referred more to install classic module and migrate to ARM.

![image](https://user-images.githubusercontent.com/79573299/221187346-251efbb5-26d2-47eb-a37e-76169fe80144.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa6c7f7-a61f-5a06-b964-888ee03eb86b
* Version Independent ID: a166875b-49f9-ea6d-d7ad-123189ef7b5c
* Content: [Install and configure the Azure PowerShell Service Management module](https://learn.microsoft.com/en-us/powershell/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0)
* Content Source: [docs-conceptual/azuresmps-4.0.0/install-azure-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/main/docs-conceptual/azuresmps-4.0.0/install-azure-ps.md)
* Service: **azure-asm**
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by SauravB-MS** [comment]
Please read my request carefully, I am suggesting  Azure classic module being incompatible with Windows powershell version 6.0/7.0.

Customers will get the below error when using windows powershell Version 6.0/7.0, which comes by default with OS 2019 and above.

***@***.***

To repro, install Azure classic module on Windows Server 2019/Server 2022 and execute Add-AzureAccount?
It should fail with the above error.

**Comment by mikefrobbins** [comment]
@SauravB-MS I've submitted an update for the message on that page to help clarify for customers who aren't aware that Windows PowerShell and PowerShell are two separate products:

![image](https://user-images.githubusercontent.com/6719572/221210266-afdf897c-0ddf-48d8-9829-6e428e07cc33.png)

**Comment by sdwheeler** [comment]
@SauravB-MS Windows PowerShell is PowerShell 5.1. Windows does not ship with a newer version of PowerShell. PowerShell 6 and higher are built on .NET (core). Windows PowerShell 5.1 uses .NET Framework 4.5 or higher.

**Comment by SauravB-MS** [comment]
Sean, Mike thanks for the clarity. Updated message should help drive more clarity for users.
