### ISSUE TITLE
No documentation for Login-AzureRmAccount usage in China.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-docs-powershell#274]
Please see [Azure/azure-powershell#1463](https://github.com/Azure/azure-powershell/issues/1463).

Need online help example for national clouds and some popinters from the getting started docs on azure.com.

**Comment by TaraMeyer** [comment]
@twitchax  why is this an issue in the docs repo?  This fix must be made upstream in the MDs in your source repo in order for this fix to flow into future releases.  Additionally, I don't even know who the contact is for this module or what module this cmdlet belongs to.

**Comment by twitchax** [comment]
I actually thought that the best place for the fix would be "Login" in the conceptual docs.

**Comment by TaraMeyer** [comment]
@sdwheeler - have you seen this?  Is this something that you could add to the conceptual docs?

**Comment by sdwheeler** [comment]
@twitchax - We need details or you can edit the conceptual docs yourself and submit a PR.

**Comment by twitchax** [comment]
It's actually pretty straightforward as the other bug mentions.

```bash
Login-AzureRmAccount -EnvironmentName AzureChinaCloud
```

It would just be nice to have a short section on it.

**Comment by sdwheeler** [comment]
Added note to the Login article. See https://github.com/Azure/azure-docs-powershell/pull/310
