### ISSUE TITLE
No documentation or details on how to gather required information

### ISSUE THREAD

**Issue by bstreet1967** [Azure/azure-docs-powershell#301]
I am trying to create recovery plans for roughly 300 servers using PowerShell.  The plans are incredibly simple, literally the same as walking through the wizard.  The problem I am having is finding out how to gather the variables that PS asks for.

For example.  PrimaryFabric,  I am hosting my servers internally and replicating to Azure. I have no idea how to find this value and I am finding nothing when looking on google or youtube.  When I gathered the information on my existing failover plans they don't include this information.

How can I get the information I need to utilize PS for this purpose?

**Comment by TaraMeyer** [comment]
@bstreet1967 - the better forum for this question is the Azure src repo. I would open an issue here:  https://github.com/Azure/azure-powershell/issues.  This repo is for documentation of reference content.  If you need specific cmdlet level questions on how to complete the functionality you describe - I would ask the Compute or VM team @twitchax  any recommendations for the best forum for this question?

**Comment by twitchax** [comment]
Is this about the Service Fabric cmdlets for PowerShell or the AzureRM cmdlets for PowerShell?

**Comment by TaraMeyer** [comment]
@bstreet1967  - can you please answer the question above?

**Comment by bstreet1967** [comment]
AzureRM.  I spoke to the devs this afternoon.  They were able to get my
question answered.

**Comment by TaraMeyer** [comment]
@bstreet1967  ok thank you.  Closing this issue.
