### ISSUE TITLE
Failure with  get-AzureRmDiagnosticSetting for SA Job

### ISSUE THREAD

**Issue by dewanymca** [Azure/azure-docs-powershell#307]
I hope Stream analytic support diagnostic and Metric from powershell(I can manually enable using portal). However using script it’s failing with error.

get-AzureRmDiagnosticSetting : Object reference not set to an instance of an object.

**Comment by TaraMeyer** [comment]
@twitchax - any recommendations for help with this cmdlet from AzureRM.Insights?

**Comment by twitchax** [comment]
@dewanymca, please file this against the product (http://github.com/Azure/azure-powershell).

**Comment by TaraMeyer** [comment]
@twitchax  thanks! @dewanymca  closing this issue.
