### ISSUE TITLE
SubscriptionID

### ISSUE THREAD

**Issue by SquirrelAssassin** [Azure/azure-docs-powershell#320]
I just ran get-azurermsubscription the output has changed and is breaking code

Expected
Subscription Name : Contoso Subscription 1
SubscriptionId    : xxxx-xxxx-xxxx-xxxx
TenantId          : yyyy-yyyy-yyyy-yyyy

Returned Values
Subscription Name : Contoso Subscription 1
**Id    : xxxx-xxxx-xxxx-xxxx**
TenantId          : yyyy-yyyy-yyyy-yyyy

**Comment by TaraMeyer** [comment]
@SquirrelAssassin - please file this issue on the source code repo:  https://github.com/Azure/azure-powershell

**Comment by SquirrelAssassin** [comment]
did you just close a issue without doing anything? typical

**Comment by TaraMeyer** [comment]
@SquirrelAssassin - you filed the issue on the content repo.  In order to have your issue addressed, you need to create this issue in the code source repo here: https://github.com/Azure/azure-powershell.  This is the direct channel to the developers who created this cmdlet.
