### ISSUE TITLE
create azure ad application and change / set manifest and permissions

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-docs-powershell#340]
Hi,

I'm trying to automate the creation of the Azure AD Application for the project I'm working at this moment using "New-AzureRmADApplication". However, I could not find a way to change settings of the manifest (e.g "oauth2AllowImplicitFlow": true).

Also, I would like to find a way to specify the permissions for this application. Is there a way to achieve that using powershell?

**Comment by TaraMeyer** [comment]
Hi @thdotnet, thank you for reaching out with your question.   This repo is the content repo and we are unfortunately not able to answer your technical question in this channel.  However, the source repo is a better channel to ask this question and get advice directly from the devs.  The code source repo is located here  https://github.com/Azure/azure-powershell/issues.  Please let me know if you have any other questions.

**Comment by TaraMeyer** [comment]
@thdotnet - another channel to ask this question is to comment on the cmdlet page as well.  I do believe that the writers who own that module monitor for questions.  You can access here:  https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/new-azurermadapplication?view=azurermps-4.1.0.  Take care always.
