### ISSUE TITLE
Microsoft.Azure.Commands.Management.IotHub.Models.PSOperationsMonitoringProperties

### ISSUE THREAD

**Issue by HowardHoffman** [Azure/azure-docs-powershell#342]
What are examples of valid setting here?

We have a Stream Analytics job that receives input from the "Operations monitoring" Endpoint of an IOT Hub.  This works only when the various "Monitoring categories" are set to something other than "None" --which is the default.  The code in https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/IotHub/Commands.IotHub/Models/PSOperationsMonitoringProperties.cs isn't very helpful.

Noting https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-operations-monitoring, do we supply a set of key/value pairs, such as:
```
{"DeviceIdentityOperations", "Verbose"},
{"DeviceTelemetry", "Verbose"},
{"C2DCommands", "Error"} ,
{"Connections", "Verbose"},
{"fileUpload", "Error"} ,
{"routes", "Verbose"}
...
```

How does one fully populate the 'Operations monitoring" Azure Portal blade of an IoT Hub via PowerShell?

**Comment by TaraMeyer** [comment]
Hi @HowardHoffman thank you for reaching out.  The best channel for your question is in the source repo that you link to above - that's the channel the devs monitor who own the IoT module.  Please file your question here https://github.com/Azure/azure-powershell/issues.  Another option is to add a comment to the specific page where you think this information is missing or unclear (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-operations-monitoring).  Please let me know if you have any other questions.

**Comment by HowardHoffman** [comment]
Thanks @TaraMeyer .  A quick experiment using `{"C2DCommands", "Error"}` and the Set-AzureRmIotHub, with that value set into the `PSOperationsMonitoringProperties.OperationMonitoringEvents` dictionary as I'd guess did succeed.  I will post this to the docs.microsoft.com page.

**Comment by TaraMeyer** [comment]
@HowardHoffman that's wonderful news and thank you for sharing with the community.  Take care always.
