### ISSUE TITLE
Get-AzureRmIoTHubConnectionString returns inaccurate Connection String syntax

### ISSUE THREAD

**Issue by starkfell** [Azure/azure-docs-powershell#344]
When running the Get-AzureRmIoTHubConnectionString using standard parameters, all Connection Strings that are returned are showing the key/value pair for the Shared Access Key Name are displaying it as ShareAccessKeyName instead of SharedAccessKeyName.

This behavior is occuring in the Modules for Azure 4.1.0 and AzureRm.IoTHub 2.1.0, but not in modules Azure 4.0.2 and AzureRm.IoTHub 2.0.1 as shown below:

![screenshot001](https://user-images.githubusercontent.com/2753909/27479245-70acb89e-5813-11e7-95b2-ba5ed6ade075.jpg)

![screenshot006](https://user-images.githubusercontent.com/2753909/27479243-6ec5692c-5813-11e7-8ff4-537587bc6a96.jpg)

**Comment by TaraMeyer** [comment]
@starkfell - thank you for sharing this information.  Could you please report this issue to the devs to make sure they address?  The best channel to reach the devs that own this module is at the Azure source repo here:  https://github.com/Azure/Azure-PowerShell/issues.  Please let me know if you have any questions.

**Comment by starkfell** [comment]
@TaraMeyer - thanks for the quick response! - resubmitted per your request - https://github.com/Azure/azure-powershell/issues/4190
