### ISSUE TITLE
New-AzureRmAvailabilitySet cmdlet

### ISSUE THREAD

**Issue by Lanwin2010** [Azure/azure-docs-powershell#356]
Hi,
I was using New-AzureRmAvailabilitySet cmdlets to create a new Availability Set. The Sku default value appears to be set to “Managed” which translates to “Aligned” upon execution. However, I am aware that there is  a Classic “Sku” as well which is unmanaged. There isn’t a lot of information available in MS documentations to specify what the exact difference between managed and unmanaged is. I am assuming this has something to do with managed disks and unmanaged disks. Which value should I use if I need to use "unmanaged" disks. "unmanaged" parameter does not get accepted and neither does "Classic". I checked CLI to create a new availability set and there seems to be a parameter "unmanaged". Also the same can be done via the portal.

Could you let me know if “Aligned” is the default for the “Sku” parameter using PowerShell or is it possible to replace “managed” with say “unmanaged” or “Classic” during the execution? 
![image](https://user-images.githubusercontent.com/29958781/27928374-935e4b3e-62ac-11e7-8c26-7fbfe8d22524.png)

Thanks,
Loy

**Comment by TaraMeyer** [comment]
Hi @Lanwin2010 thank you for reaching out.  I believe we also spoke over Skype, but I'm not sure if you left this comment after or before our conversation.  The best channel for this question is on the source code repo here:  https://github.com/Azure/Azure-PowerShell/issues.  The source repo is a direct line to the developers who created the cmdlet your question relates to.  Another option, that we discussed, is to leave a comment on the actual topic.  To do this, you need to navigate to the topic on docs here:  https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermavailabilityset?view=azurermps-4.1.0:

![image](https://user-images.githubusercontent.com/14112499/27972916-d7d632da-630c-11e7-9227-d457f2967f70.png)

If you continue to have issues please feel free to reach out.

Take care!

**Comment by Lanwin2010** [comment]
Got it. Thanks a lot TaraMeyer.
