### ISSUE TITLE
New-AzureRmVirtualNetworkGateway.md

### ISSUE THREAD

**Issue by weeyin83** [Azure/azure-docs-powershell#373]
The changes that I made to the "New-AzureRmVirtualNetworkGateway" document are visible but I am not listed as a contributor - can you please advise?

**Comment by sdwheeler** [comment]
@weeyin83 You are shown as a contributor to that article in GitHub. It should show up when the new documentation is published for the 4.3.1 release. That should happen next week.

**Comment by sdwheeler** [comment]
@weeyin83 After further review, the cmdlet reference topics don't show contributors on the webpage view. But you are listed as a contributor in GitHub.
