### ISSUE TITLE
Docs link 404

### ISSUE THREAD

**Issue by alexeldeib** [Azure/azure-docs-powershell#400]
[This page](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azurermps-4.3.1) on service principals links at the top to create a service principal in the portal. It points to a dead link:

https://docs.microsoft.com/en-us/powershell/azure/resource-group-create-service-principal-portal?view=azurermps-4.3.1

Should probably be: 

https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal

I notice in [this markdown file](https://github.com/Azure/azure-docs-powershell/blob/master/azureps-cmdlets-docs/ResourceManager/docs-conceptual/create-azure-service-principal-azureps.md) 404'd doc gets referenced a relative path, /azure/azure-resource-manager/resource-group-create-service-principal-portal, but the powershell docs sit under https://docs.microsoft.com/en-us/powershell, so the relative URL has an extra "/powershell" that shouldn't be there.

**Comment by TaraMeyer** [comment]
Hi @alexeldeib  - thank you for pointing this out!  @sdwheeler  - seems like a simple fix.  Did you want to make the update, or should I?

**Comment by sdwheeler** [comment]
@alexeldeib @TaraMeyer - I will investigate

**Comment by sdwheeler** [comment]
@alexeldeib - I am not seeing the problem you described. I looked at the published article and the link works for me.

**Comment by alexeldeib** [comment]
Looks like however the relative URLs were constructed works fine now, sorry for the trouble!
