### ISSUE TITLE
New-AzureRMAutomationConnection documentation is out of date

### ISSUE THREAD

**Issue by arcotek-ltd** [Azure/azure-docs-powershell#419]
Errors in example (Source: AzureRM.Automation (Version 3.4.0)):
The hashtable for the parameter `-ConnectionFieldValues` needs the following keys:

- CertificateAssetName 
- SubscriptionID 
- SubscriptionName

So in example1, you need to **add** SubscriptionName and **change** AutomationCertificateName to CertificateAssetName, otherwise an error is generated, saying the AutomationAccount doesn't exist. Which is equally unhelpful. 

It would also help if you added the allowed values for `-ConnectionTypeName` which are:

- Azure
- AzureClassicCertificate
- AzureServicePrincipal

(An explanation of each of the above would be helpful too)

**Referenced Document:** 

- [https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/new-azurermautomationconnection?view=azurermps-4.4.0](https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/new-azurermautomationconnection)

- [https://github.com/Azure/azure-docs-powershell/blob/master/azureps-cmdlets-docs/ResourceManager/AzureRM.Automation/v3.4.0/New-AzureRMAutomationConnection.md](https://github.com/Azure/azure-docs-powershell/blob/master/azureps-cmdlets-docs/ResourceManager/AzureRM.Automation/v3.4.0/New-AzureRMAutomationConnection.md)

**Comment by TaraMeyer** [comment]
@arcotek-ltd - thank you very much for providing these helpful suggestions.  @sdwheeler  will be adding the edits to the source repo to ensure the next version of docs we publish has these important updates included in the next release.

**Comment by sdwheeler** [comment]
Copied issue to the source repo to the proper dev resource can update the documentation.

**Comment by mdeery** [comment]
I receive the following error when trying to execute 

New-AzureRmLogicApp -ResourceGroupName "rsg-hcms-itsms-eds-candidate" -Name "la-hcms-itsms-eds-candidate" -DefinitionFilePath $(System.DefaultWorkingDirectory)/$(Release.DefinitionName)/drop/LogicApp.json -ParameterFilePath $(System.DefaultWorkingDirectory)/$(Release.DefinitionName)/drop/LogicApp.parameters.dev.json -Location "australiasoutheast" -State "Enabled"

##[error]Unexpected character encountered while parsing value: h. Path '', line 0, position 0.

**Comment by TaraMeyer** [comment]
@sdwheeler  - do you happen to know if this pr made it into the latest release?

**Comment by sdwheeler** [comment]
@TaraMeyer - doesn't look like the docs have been updated yet.

**Comment by TaraMeyer** [comment]
@sdwheeler - yes I'm aware. I wasn't cIear.  Can you confirm if the pr you created in the source was accepted?

**Comment by sdwheeler** [comment]
@TaraMeyer - I did not create any PR for this. There is an issue in the source repo. It is a copy of this issue because the dev team works in the source repo.

**Comment by TaraMeyer** [comment]
@sdwheeler are we able to close on this?

**Comment by sdwheeler** [comment]
@TaraMeyer The https://github.com/Azure/azure-powershell/issues/4684 Issue is still open. They have to fix it in source first.

**Comment by sptramer** [comment]
@twitchax Escalating for engineering team triage since this issue has been open >6mo.

**Comment by twitchax** [comment]
I recommend closing this in favor of the issue in the product repo.

@vrdmr, can you please close or address the bug in the product repo?

Azure/azure-powershell#4684

**Comment by sptramer** [comment]
@arcotek-ltd For updates, please follow https://github.com/Azure/azure-powershell/issues/4684 as the engineering team resolves the issue in generated documentation.
