### ISSUE TITLE
Publish-AzureWebsiteProject does not work when *.zip is created via Compress-Archive

### ISSUE THREAD

**Issue by PiotrKowalski93** [Azure/azure-docs-powershell#441]
Hello,

I am working on build and deploy script. First I have to prepare deploy.zip package. To do that I was using Compress-Archive in my build script, but when I tried to use:

`Publish-AzureWebsiteProject -Name ServiceName -Package "XXXXX\deploy.zip"`

I got an Error:

> Publish-AzureWebsiteProject : (xx.xx.xxxx,xx:xx) An error occurred when the request was processed on the remote computer.

Only 80% of files were deployed in Azure App Service. All static files were missing.
But when took that package -> uzip -> righ click -> send to -> Compressed folder
I was able to deploy all files. When I used _7za.exe_ in my build script  all files were deployed.

Do you know what is the issue here?

**Comment by TaraMeyer** [comment]
Hello @PiotrKowalski93 - the best place for this question is at the source repo.  The source repo (https://github.com/Azure/azure-powershell/issues) is the direct line to the devs who own the Azure module.  May I also suggest that you label your issue with "help wanted".

Please let me know if you have any other question!  Take care.

Tara

**Comment by PiotrKowalski93** [comment]
Hello Tara, Thank you for help. I moved the issue.

**Comment by TaraMeyer** [comment]
@PiotrKowalski93  thank you for letting me know.  Take care always!
