### ISSUE TITLE
how to solve this?

### ISSUE THREAD

**Issue by ayushi1301** [Azure/azure-docs-powershell#477]
PS E:\infrastructure_samples> Get-AzureRmRecoveryServicesBackupProtectionPolicy
Get-AzureRmRecoveryServicesBackupProtectionPolicy : Could not load file or assembly 'Microsoft.Azure.Commands.RecoveryServices.Backup.ServiceClientAdapter, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Get-AzureRmRecoveryServicesBackupProtectionPolicy
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmReco...rotectionPolicy], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.GetAzureRmRecoveryServicesBackupProtectionPolicy

**Comment by sdwheeler** [comment]
Try reinstalling the AzureRM module. If that does not work, contact Azure Support https://azure.microsoft.com/en-us/support/options/.

**Comment by jeffpatton1971** [comment]
So, perhaps you all could find a better way to notify us that a change has occurred in the powershell modules other than throwing a nasty red error, that will then generate noise in the repo.
