### ISSUE TITLE
Should Azure.Commands.*.Models classes be documented?

### ISSUE THREAD

**Issue by jmlane** [Azure/azure-docs-powershell#491]
Hello!

I've noticed in the documentation that there are no links to the datatypes of any of the Model classes used to pass data or configuration to the Azure endpoints. After a quick inspection of the repository and that of the azure-powershell module, it seems like there is no documentation for these specific Powershell classes.

I think having model class reference documentation that is linked from the command documentation would be a valuable addition to the documentation. I know you can view the [SDK model classes](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.protocol.models?view=azure-dotnet) or the [REST API schema](https://docs.microsoft.com/en-us/rest/api/batchservice/) in other documentation but that is an extra complication for users of the Powershell module to mentally map those structures to the Powershell equivalent.

Is this a change that would be welcome? Is there tooling available to the community to the generate the desired page templates from the Powershell module source files?

**Comment by sptramer** [comment]
@twitchax Looks like a product enhancement (a very old one.) @jmlane you may receive a faster response if you open your request with the engineering team: https://github.com/azure/azure-powershell/issues

**Comment by jmlane** [comment]
Thanks. Cross-posted as suggested.

**Comment by jmlane** [comment]
Looks like https://github.com/Azure/azure-powershell/issues/5777 covers the path forward to getting this gap in the documentation filled. I'm closing this issue, as it seems redundant.

**Comment by twitchax** [comment]
Thanks, all!  We are actually currently working on this.
