### ISSUE TITLE
Login-AzureRmAccount : The term 'Connect-AzureRmAccount' is not recognized

### ISSUE THREAD

**Issue by vtjc2002** [Azure/azure-docs-powershell#500]
Powershell installed via brew
and installed Azure Powershell per https://docs.microsoft.com/en-us/powershell/azure/install-azurermps-maclinux?view=azurermps-5.2.0

When I tried to login, I get the following error.

Login-AzureRmAccount : The term 'Connect-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Login-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by TaraMeyer** [comment]
Hi @vtjc2002 - the best place to get help on this error is via the src repo where the devs keep code and content.  Please copy and paste your open question to:  https://github.com/Azure/azure-powershell/issues and do let me know if you don't get the help you need.  Thanks!
