### ISSUE TITLE
Some of the commands are missing from the module

### ISSUE THREAD

**Issue by yurykissin** [Azure/azure-docs-powershell#517]
For example, I use 
Add-AzureADDeviceRegisteredUser
which is part of the AzureAD module and not present in the AzureRM.Profile module.

**Comment by TaraMeyer** [comment]
@yurykissin -thank you for reaching out.  Could you please provide more context, from your message I'm unclear what exactly you need help with.  Thanks!

**Comment by yurykissin** [comment]
Hi Tara, thx for your reply!
I have already managed to solve this issue, it was something I missed on my end.

**Comment by TaraMeyer** [comment]
Perfect!  Thank you for the update.
