### ISSUE TITLE
 Missing documentation on an equivalent in REST API for Move-AzureReservedIP cmdlet

### ISSUE THREAD

**Issue by meetamitbhatia** [Azure/azure-docs-powershell#546]
Customer wants to automate the migration of Classic environments to ARM, part of which includes migrating a few public IP addresses from Classic to ARM.  
We see that there's documentation for Move-AzureReservedIP PowerShell cmdlet at https://docs.microsoft.com/en-us/powershell/module/azure/move-azurereservedip?view=azuresmps-4.0.0, but we could not find any documentation on the equivalent in the REST API. We had to Debug Move-AzureReservedIP cmdlet to confirm REST API,
https://management.core.windows.net/3a0ecc28-a2ef-4d17-ac52-01f0c4884841/services/networking/reservedips/testmoveip/migration?comp=prepare

Can we document above REST API?

**Comment by TaraMeyer** [comment]
@twitchax  are you able to add the REST API author to this issue?

**Comment by TaraMeyer** [comment]
@meetamitbhatia - may I recommend that you log this question in the Azure Resource Manager src repo here:  https://github.com/Azure/azure-powershell/issues.  This is mainly the docs repo and technical questions for the Azure team are only reviewed in the src repo.  Thanks!

**Comment by meetamitbhatia** [comment]
Logged the question as suggested:
https://github.com/Azure/azure-powershell/issues/5924

**Comment by sptramer** [comment]
Closing since an issue has been opened with the PowerShell engineering team.
