### ISSUE TITLE
Save-AzureRmVMImage.md needs more detailed description of "-Path" parameter

### ISSUE THREAD

**Issue by wellsluo** [Azure/azure-docs-powershell#603]
In the doc of Save-AzureRMVMImage has following description of "-Path" parameter, which is very confusing:
[Save-AzureRmVMImage.md](https://github.com/Azure/azure-docs-powershell/blob/master/azurermps-6.2.0/AzureRM.Compute/Save-AzureRmVMImage.md)
```
-Path
Specifies the path of the VHD.
```
Question is: what is the "path" of VHD? local path to save VHD copy locally?

But in the source code file, it has following help message:
[SaveAzureVMImageCommand.cs](https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Action/SaveAzureVMImageCommand.cs)
```
        [Parameter(
           Position = 5,
           ValueFromPipelineByPropertyName = true,
           HelpMessage = "**The file path in which the template of the captured image is stored**")]
        [ValidateNotNullOrEmpty]
        public string Path { get; set; }
```
The message in source code is totally different from the description message in the doc.  Please make sure how on earth the "-Path" parameter is used.

**Comment by sptramer** [comment]
Local command help is handled as part of the non-docs product. Issue has been duplicated as https://github.com/Azure/azure-powershell/issues/6385
