### ISSUE TITLE
New-AzureRmNetworkSecurityGroup Invalid Address & Port Entries

### ISSUE THREAD

**Issue by bdyzel** [Azure/azure-docs-powershell#605]
Basic single or range entries work, but multiple entries can't be entered via the powershell commands.

**For instance this would work;**
$rule1 = New-AzureRmNetworkSecurityRuleConfig -Name rdp-rule -Description "Allow RDP"
    -Access Allow -Protocol Tcp -Direction Inbound -Priority 100 -SourceAddressPrefix
    Internet -SourcePortRange * -DestinationAddressPrefix * -DestinationPortRange 3389

**but this command entering multiple destination or source PortRange's/AddressPrefix's won't:**
$rule1 = New-AzureRmNetworkSecurityRuleConfig -Name rdp-rule -Description "Allow RDP"
    -Access Allow -Protocol Tcp -Direction Inbound -Priority 100 -SourceAddressPrefix
    Internet -SourcePortRange * -DestinationAddressPrefix "192.168.10.0/24,192.168.11.0/24" -DestinationPortRange "3389,22"

NSG's do cater for multiple entries, the powershell or command options to configure these don't.

**Comment by sptramer** [comment]
@bdyzel Please file an issue about this with the engineering team at https://github.com/azure/azure-powershell/issues - this seems like a product bug or reference documentation issue, and they handle both.
