### ISSUE TITLE
Connect-AzureRmAccount Does Not Exist

### ISSUE THREAD

**Issue by brentlightsey** [Azure/azure-docs-powershell#610]
I see this message when using the "Connect-AzureRmAccount": "The term 'Connect-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program." Check Issue #552: https://github.com/Azure/azure-docs-powershell/issues/552

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aab3bee-a330-3875-cbe8-5dfe07e23d29
* Version Independent ID: cc8aa9be-2707-4ef6-e4d9-35498b837289
* Content: [Get started with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/get-started-azureps?view=azurermps-6.2.0)
* Content Source: [docs-conceptual/azurermps-6.2.0/get-started-azureps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.2.0/get-started-azureps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Can you please provide some more information?

* Install platform
* Install method
* Installed version (`Get-Module AzureRM -ListAvailable | Select-Object -Property Name,Version,Path`)

**Comment by sgoings** [comment]
I'm running into this too:

```
PS /Users/sgoings> Connect-AzureRmAccount
Connect-AzureRmAccount : The term 'Connect-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Connect-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

PS /Users/sgoings> Login-AzureRmAccount
Login-AzureRmAccount : The term 'Login-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Login-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Login-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```

- MacOS
- Installed AzureRM via
  ```
  Install-Module -Name AzureRM -AllowClobber
  Import-Module -Name AzureRM
  ```
- Version
  ```
  Get-Module AzureRM -ListAvailable | Select-Object -Property Name,Version,Path

  Name    Version Path
  ----    ------- ----
  AzureRM 6.2.1   /usr/local/share/powershell/Modules/AzureRM/6.2.1/AzureRM.psd1
  ```

**Comment by twitchax** [comment]
This is not an issue with the docs or the Core version of the modules: these are the wrong modules.

`AzureRM` does not work on Linux: you must install `AzureRM.Netcore`.

**Comment by sgoings** [comment]
Confused how I should proceed here. Which repo's issue queue would be the best place to raise awareness that Azure PowerShell is not working on non-Windows hosts?

**Comment by sptramer** [comment]
@sgoings If this is a documentation issue that you experienced, then this is the appropriate place. There are upcoming changes to the installation documentation which will hopefully make it clearer that AzureRM is not suitable for non-Windows hosts.

@twitchax On the engineering side, is there a way to get better warnings/errors for hosts which require .NET Core when attempting to run a .NET Framework application?

**Comment by twitchax** [comment]
This question may be better for @joeyaiello.  I agree that the error is not helpful, but it might be something for the PowerShell Core team to look into for all modules that do not work in PS Core.

However, for Azure PowerShell specifically, this should resolve itself when we move to NET Standard in August/September timeframe.

**Comment by sptramer** [comment]
Documentation updates regarding appropriate platforms are in #621. Closing this issue.
