### ISSUE TITLE
Guidance on uninstalling older versions of Azure RM PS 

### ISSUE THREAD

**Issue by jayeshdshah** [Azure/azure-docs-powershell#611]
"If you have an earlier version of the Azure PowerShell modules installed from the PowerShell Gallery and would like to update to the latest version, Update-Module installs the new version side-by-side with the old version. It does not remove the old version."
Ref: https://github.com/Azure/azure-powershell

My issue is that I have two versions installed side by side on my machine and I only want to maintain/keep latest version of it. So Can we have any proper documentation to uninstall the older versions (without effecting any other applications installed on my machine like VS Code or Visual studio).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86e00a52-d1da-17e1-294a-b99849942814
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install and configure Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.2.0#step-1-install-powershellget)
* Content Source: [docs-conceptual/azurermps-6.2.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.2.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@jayeshdshah - This work is in progress right now. There will be documentation updates soon detailing how to install, properly upgrade, and uninstall versions of Azure PowerShell.

**Comment by rajrao** [comment]
-AllowClobber doesnt seem to work for "Install-Module -Name AzureRM -AllowClobber". Instead, one needs to use -Force

**Comment by sptramer** [comment]
Resolved by #621. Please let us know if there are other improvements you'd like to see.
