### ISSUE TITLE
Issue Get Azure VM status same commands but different status

### ISSUE THREAD

**Issue by cloudmelon** [Azure/azure-docs-powershell#617]
The commands : 
$vms = Get-AzureVM  ( here have some information of Azure VM , the status of VM is : StoppedDeallocated )

But while foreach it 

Foreach ($vm in $vms) { 

// here I am printing the $vm with Vm status (  it displays stopped ) 
}
Issue Get Azure VM status same commands but different status

![image](https://user-images.githubusercontent.com/4621560/41417191-e9da424e-6fec-11e8-9e7d-71640e6dfa66.png)

**Comment by sptramer** [comment]
@cloudmelon Receiving the different status for the same machine seems like a product bug. Can you please file an issue with the Azure PowerShell engineering team at https://github.com/azure/azure-powershell/issues ?

**Comment by cloudmelon** [comment]
OK. I reported to the product team as well. Thanks :)
