### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by cbailiss** [Azure/azure-docs-powershell#630]
Under the heading "Install or update the Azure PowerShell module", re the command "Install-Module -Name AzureRM -AllowClobber", the note says "This command will update any existing installation of Azure PowerShell on your system".
However, running that command on my system at an administrator prompt says "WARNING: Version '5.1.1' of module 'AzureRM' is already installed at 'C:\Program Files\WindowsPowerShell\Modules\AzureRM\5.1.1'. To install version '6.3.0', run Install-Module and add the -Force parameter, this command will install version '6.3.0' in side-by-side with version '5.1.1'.".
So, the information provided by this page is wrong.  What is the correct procedure to update?  I don't want side-by-side.
Please understand that getting documentation like this right is important.
When a new version is released, one of the first questions people have is "How should I update?"
Really, such documentation should be viewed as a key part of the release itself.  
To not do so is very frustrating for users and it just seems like, let's throw the software out there and people can figure the rest out for themselves...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140cfec3-6b83-ceac-f220-94319dc78d67
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.3.0)
* Content Source: [docs-conceptual/azurermps-6.3.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.3.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
I understand that seeing documentation issues like this is frustrating. Right now there is a major documentation update underway to be published live sometime this week, which will update the install instructions to be accurate regarding version management and include instructions on how to remove older versions.

**Comment by sptramer** [comment]
This has been resolved by #621. Please let us know if there are any other needed improvements.
