### ISSUE TITLE
Is Import-Module AzureRM necessary?

### ISSUE THREAD

**Issue by cbailiss** [Azure/azure-docs-powershell#635]
Under "Sign In" the example states:
```
# Import the module into the PowerShell session
Import-Module AzureRM
# Connect to Azure with an interactive dialog for sign-in
Connect-AzureRmAccount
```

Is "Import-Module AzureRM" strictly necessary?  It takes some time and the sign-in seems to work fine in a new PowerShell window (for me at least) without it.  I believe I read (on a blog somewhere) that this can be skipped on more recent versions of PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140cfec3-6b83-ceac-f220-94319dc78d67
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.3.0)
* Content Source: [docs-conceptual/azurermps-6.3.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.3.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This behavior is apparently affected by `$PSModuleAutoLoadingPreference`. Based on feedback from other PowerShell writers, the decision was made to ensure that the `Import-Module` instructions remain to make sure that the sign-in process works on all users' systems.
