### ISSUE TITLE
How to install powershell v5.0 in MacOS or Linux?

### ISSUE THREAD

**Issue by bingosummer** [Azure/azure-docs-powershell#636]
To install Powershell for Azure Stack, PowerShell 5.0 is required. See https://github.com/MicrosoftDocs/azure-docs/issues/11030.
Could you please document how to install powershell 5.0 in MacOS or Linux?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 516e7d5a-4a95-7fab-a21a-59df293d3f97
* Version Independent ID: 4baba292-2a6e-3a0f-a6bf-7e00356a95e8
* Content: [Install Azure PowerShell on macOS or Linux](https://docs.microsoft.com/en-us/powershell/azure/install-azurermps-maclinux?view=azurermps-6.3.0)
* Content Source: [docs-conceptual/azurermps-6.3.0/install-azurermps-maclinux.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.3.0/install-azurermps-maclinux.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
PowerShell 5.0 is not available for Mac or Linux. Only PowerShell 6.0 and above, which use portable .NET libraries, are. You can find instructions on how to install PowerShell 6.0 here:
* [macOS install](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-macos?view=powershell-6)
* [Linux install](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6)

It is very likely that the Azure Stack modules are __not__ compatible with PowerShell 6.0. @twitchax do you know who to contact about Stack portability?
