### ISSUE TITLE
What are credentials for a service principal?

### ISSUE THREAD

**Issue by jnprakash** [Azure/azure-docs-powershell#640]
What do you mean by 'service principal user ID and password', is it referring to the keys? I tried it and does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ceb52044-f648-d04c-cf5a-860ad5656f9f
* Version Independent ID: b814f076-657c-206b-b16e-c7f137bff744
* Content: [Sign in with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azurermps-6.4.0)
* Content Source: [docs-conceptual/azurermps-6.4.0/authenticate-azureps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.4.0/authenticate-azureps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Please see the linked documentation describing service principals. https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azurermps-6.4.0

**Comment by jnprakash** [comment]
I have created a service principal an year ago which did not ask for any password. Is this something new with the latest Azure version? How do we assign a password for an existing service principal?
