### ISSUE TITLE
Add-AzureRmMetricAlertRule: Should parameter 'description' be mandatory?

### ISSUE THREAD

**Issue by ofaruk09** [Azure/azure-docs-powershell#642]
Add-AzureRmMetricAlertRule parameter Description is mandatory but creating an alert (classic) within the azure portal is not mandatory. 

This means in the scenario of copying an existing rule where there is no description (i.e. it was created without a description within the portal) fails parameter validation for the cmdlet given the properties are mapped.

# GET THE RULE
$rule = Get-AzureRmAlertRule -ResourceGroupName $RG
# RE ADD THE RULE
        Add-AzureRmMetricAlertRule `
            -ResourceGroupName $RG `
            -TargetResourceId $rule.Condition.DataSource.ResourceUri `
            -Location $rule.Location `
            -Name $rule.AlertRuleResourceName `
            -Description $rule.Description ` <-- This is null, causing validation to fail
            -MetricName $rule.Condition.DataSource.MetricName `
            -Operator $rule.Condition.OperatorProperty `
            -Threshold $rule.Condition.Threshold `
            -WindowSize $rule.Condition.WindowSize `
            -TimeAggregationOperator $rule.Condition.TimeAggregation

**Comment by sptramer** [comment]
This looks like a product bug/reference issue. Can you please file a ticket on the engineering product? https://github.com/azure/azure-powershell/issues/
