### ISSUE TITLE
Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified while run 'Import-Module AzureRM'.

### ISSUE THREAD

**Issue by xsqian** [Azure/azure-docs-powershell#644]
PS /Users/xsqian&gt; Install-Module -Name AzureRM                                                                                                                         
PS /Users/xsqian&gt; # Import the module into the PowerShell session                                                                                                      
PS /Users/xsqian&gt; Import-Module AzureRM                                                                                                                                
Import-Module : Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
At /usr/local/share/powershell/Modules/AzureRM.profile/5.3.1/AzureRM.Profile.psm1:12 char:1
+ Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Microsoft.Azu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:16 char:1
+ Import-Module AzureRM.ApiManagement -RequiredVersion 6.1.1 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:20 char:1
+ Import-Module AzureRM.Batch -RequiredVersion 4.1.1 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:24 char:1
+ Import-Module AzureRM.Compute -RequiredVersion 5.2.0 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:28 char:1
+ Import-Module AzureRM.DataFactories -RequiredVersion 5.0.1 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:36 char:1
+ Import-Module AzureRM.HDInsight -RequiredVersion 4.1.4 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:39 char:1
+ Import-Module AzureRM.KeyVault -RequiredVersion 5.0.3 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:50 char:1
+ Import-Module AzureRM.RecoveryServices -RequiredVersion 4.1.4 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:51 char:1
+ Import-Module AzureRM.RecoveryServices.Backup -RequiredVersion 4.3.0  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:52 char:1
+ Import-Module AzureRM.RecoveryServices.SiteRecovery -RequiredVersion  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:53 char:1
+ Import-Module AzureRM.RedisCache -RequiredVersion 5.0.1 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:59 char:1
+ Import-Module AzureRM.Sql -RequiredVersion 4.9.0 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
Import-Module : Assembly with same name is already loaded
At /usr/local/share/powershell/Modules/AzureRM/6.4.0/AzureRM.psm1:60 char:1
+ Import-Module AzureRM.Storage -RequiredVersion 5.0.0 -Global
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
+ FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand
 
PS /Users/xsqian&gt; # Connect to Azure with an interactive dialog for sign-in                                                                                            
PS /Users/xsqian&gt; Connect-AzureRmAccount                                                                                                                               
Connect-AzureRmAccount : The term 'Connect-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Connect-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
 
PS /Users/xsqian&gt; 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71700c74-3a30-aec4-0fc3-1fce2010d27d
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-5.7.0)
* Content Source: [docs-conceptual/azurermps-5.7.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-5.7.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sivamani-dev** [comment]
I'm facing the same issue. Is a way to resolve it?

**Comment by MonikaReddy-MSFT** [comment]
@sivamani-dev - I'm going to assign this to the document author so they can update the work with you on this accordingly.

**Comment by mikefrobbins** [comment]
As the warning in the referenced doc states, "We do not support having both the AzureRM and Az modules installed for PowerShell 5.1 on Windows at the same time." The specified error will only occur when both the Az module and AzureRM module are installed at the same time.
