### ISSUE TITLE
Set-AzureRmWebApp : The parameter phpVersion has an invalid value

### ISSUE THREAD

**Issue by LukeDearden** [Azure/azure-docs-powershell#651]
Can no longer disable PHP using Set-AzureRmWebApp

AzureRM.WebSites version 5.0.4

Set-AzureRmWebApp no longer accept the parameter -PhpVersion Off

Getting the error

Set-AzureRmWebApp : The parameter phpVersion has an invalid value.

**Comment by sptramer** [comment]
Please file a bug report to ensure that this is not a product issue: https://github.com/azure/azure-powershell/issues

Also please include the version of the `AzureRM` module installed.

**Comment by LukeDearden** [comment]
Done, 
https://github.com/Azure/azure-powershell/issues/6635

**Comment by sptramer** [comment]
Closing; this has been resolved on the engineering side.
