### ISSUE TITLE
Documentation lacking

### ISSUE THREAD

**Issue by Powerhelmsman** [Azure/azure-docs-powershell#652]
The issue was created by @allar7 from MicrosoftDocs/feedback#496
Link to article:
https://docs.microsoft.com/en-us/powershell/module/azure/select-azuresubscription?view=azuresmps-4.0.0
Problem:
Article does not include commandlets such as Select-AzureRmSubscription which leads to not having douments for customers to look at for RM specific commands. Customer found the documentation lacking.

**Comment by sptramer** [comment]
The moniker linked from here, `azuresmps`, refers to the Azure classic deployment model. That module does not include any of the `*-AzureRm*` commands.

**Comment by allar7** [comment]
My apologies, I linked the other article I was looking at. I meant to point at the following article:
https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/set-azurermcontext?view=azurermps-6.4.0
Where Select-AzureRmSubscription is not listed with the others.

**Comment by sptramer** [comment]
Engineering handles reference documentation generation. Please file a bug indicating the missing cmdlet documentation with that team: https://github.com/azure/azure-powershell/issues

**Comment by allar7** [comment]
Thanks!
