### ISSUE TITLE
Backup-AzureKeyVaultKey

### ISSUE THREAD

**Issue by waheedhussain** [Azure/azure-docs-powershell#657]
Hi,

does the following command support export to blob storage?

azure-docs-powershell/azurermps-2.2.0/AzureRM.KeyVault/Backup-AzureKeyVaultKey.md

Thanks,
Waheed

**Comment by sptramer** [comment]
Please see the documentation, which describes the behavior of the cmdlet and where information is stored.

> The Backup-AzureKeyVaultSecret cmdlet backs up a specified secret in a key vault by downloading it and storing it in a file. If there are multiple versions of the secret, all versions are included in the backup. Because the downloaded content is encrypted, it cannot be used outside of Azure Key Vault. You can restore a backed-up secret to any key vault in the subscription that it was backed up from.

 https://docs.microsoft.com/en-us/powershell/module/azurerm.keyvault/backup-azurekeyvaultsecret?view=azurermps-6.4.0
