### ISSUE TITLE
AzureRmVmDiskEncryptionStatus - extensions/AzureDiskEncryption'  not found.

### ISSUE THREAD

**Issue by Kinjara** [Azure/azure-docs-powershell#658]
Greetings,

I created a standard IAAS VM but when I want to test for encryption by the command
Get-AzureRmVmDiskEncryptionStatus, I run into the following exception:

Get-AzureRmVmDiskEncryptionStatus : The Resource 'Microsoft.Compute/virtualMachines/Test2/extensions/AzureDiskEncryption' under resource group 'EXPERIMENTTEST2' was not found.

I am running the command from the Preview version of PowerShell in Azure.

with regards,
Sebastian

**Comment by sptramer** [comment]
Please see the documentation, which describes the behavior of the cmdlet and where information is stored.

> The Backup-AzureKeyVaultSecret cmdlet backs up a specified secret in a key vault by downloading it and storing it in a file. If there are multiple versions of the secret, all versions are included in the backup. Because the downloaded content is encrypted, it cannot be used outside of Azure Key Vault. You can restore a backed-up secret to any key vault in the subscription that it was backed up from.

 https://docs.microsoft.com/en-us/powershell/module/azurerm.keyvault/backup-azurekeyvaultsecret?view=azurermps-6.4.0

**Comment by sptramer** [comment]
Closing this issue due to lack of actionable information.
