### ISSUE TITLE
document is wrong again

### ISSUE THREAD

**Issue by peterremote1980** [Azure/azure-docs-powershell#667]
see this http://peter.quantr.hk/2018/07/microsoft-azure-document-is-wrong-again/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9183934-7812-629c-ae01-ff55bd38f11d
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.5.0)
* Content Source: [docs-conceptual/azurermps-6.5.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.5.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by bc3tech** [comment]
![image](https://user-images.githubusercontent.com/1967433/43168535-8b26f55a-8f52-11e8-98d8-cd63087e1fa0.png)

**Comment by sptramer** [comment]
Link goes to 404, no action can be taken.

**Comment by brandonh-msft** [comment]
can we not delete the link?
