### ISSUE TITLE
Example output is copied when using the "copy" button in examples

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-docs-powershell#668]
When using the "Copy" button, example output is copied over instead of skipped over.  This makes it impossible to copy paste into a PowerShell session using that functionality.  I see that the copy button does strip out the "PS C:/>", so is it possible to strip out any line that does not start with "PS C:>"?

Example: https://docs.microsoft.com/en-us/powershell/module/azurerm.keyvault/add-azurekeyvaultcertificate?view=azurermps-4.4.1

**Comment by sptramer** [comment]
I've brought this to the attention of our docs backend team and we're going to start a discussion about how to possibly improve our copy/paste experience. Thanks for your input!

**Comment by sptramer** [comment]
Going to close this issue as the site engineering team is actively looking into how to improve both the copy/paste and "try it" features.
