### ISSUE TITLE
additions for  Persistent Credentials conceptual doc

### ISSUE THREAD

**Issue by sphibbs** [Azure/azure-docs-powershell#669]
https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azurermps-6.5.0 

Please add sections for
-When NOT to use enable-azurermcontextautosave e.g. azure automation
- Guidance for when to use scopes or pass a context to a cmd vs signing in.

**Comment by sphibbs** [comment]
more conceptual items from https://github.com/Azure/azure-powershell/issues/6185 

  Description of What a Context and ContextContainer are
  Differences between CurrentUser and Process scopes for Profile cmdlets
  When it is appropriate to use Context AutoSave and when (and how) it should be disabled

**Comment by sphibbs** [comment]
Not sure how / why I closed this

**Comment by sptramer** [comment]
Closing this to move to an internal ticket.
