### ISSUE TITLE
Install-Module is broken

### ISSUE THREAD

**Issue by bwmeier** [Azure/azure-docs-powershell#670]
&gt; Install-Module -Name AzureRM
Install-Module : A parameter cannot be found that matches parameter name 'Name'.
At line:1 char:16
+ Install-Module -Name AzureRM
+                ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9183934-7812-629c-ae01-ff55bd38f11d
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.5.0)
* Content Source: [docs-conceptual/azurermps-6.5.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.5.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Please provide the information about the version of `PowerShellGet` installed, by running the following command:

```
Get-Module -Name PowerShellGet -ListAvailable | Select-Object -Property Name,Version,Path
```

**Comment by bwmeier** [comment]
It looks like there are two versions installed.  I imagine I'm probably getting the old version for some reason.  The documentation should link to how to manage powershell get and troubleshoot the install.  
```
PS> Get-Module -Name PowershellGet -ListAvailable | select name, version, path

Name          Version Path
----          ------- ----
PowerShellGet 1.6.5   C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.6.5\PowerShellGet.psd1
PowerShellGet 1.0.0.1 C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PowerShellGet.psd1
```

**Comment by bwmeier** [comment]
Root cause - PSGet was installed, overriding Install-Module etc.  I had to manually delete the module from `$HOME\Documents\WindowsPowerShell\Modules` to get anything to work.  Very frustrating experience

**Comment by sptramer** [comment]
It is unclear whether or not PSGet is commonly installed software or even maintained at this point (last commit almost 1yr ago) and this issue has not been reported before. It's unlikely that information about the cmdlet name conflicts will be added to install documentation but I'll evaluate it.

**Comment by kamranayub** [comment]
Just ran into this too, my install is a bit old. I had PowerShellGet 1.0.0.1 as well.
