### ISSUE TITLE
what is RM stand for?

### ISSUE THREAD

**Issue by peterremote1980** [Azure/azure-docs-powershell#678]
what is RM stand for in the word AzureRM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac940e68-c41e-485b-c89c-057dd407fed1
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.6.0)
* Content Source: [docs-conceptual/azurermps-6.6.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.6.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by jpeebles3** [comment]
RM stands for "Resource Manager", which is a management framework that allows administrators to deploy, manage and monitor Azure resources.
