### ISSUE TITLE
Get-module can't see it

### ISSUE THREAD

**Issue by peterremote1980** [Azure/azure-docs-powershell#679]
Why i "Import-Module AzureRM" but can't see in "Get-Module" ? but command Connect-AzureRmAccount exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac940e68-c41e-485b-c89c-057dd407fed1
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.6.0)
* Content Source: [docs-conceptual/azurermps-6.6.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.6.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
You have installed with a method other than `Install-Module`, and may have auto-import enabled for available commands.
