### ISSUE TITLE
big bug

### ISSUE THREAD

**Issue by peterremote1980** [Azure/azure-docs-powershell#680]
After I do "Install-Module AzureRM.NetCore"

PS /Users/peter&gt; get-module                                                                                                                                                                   

ModuleType Version    Name                                ExportedCommands                                                                                                                   
---------- -------    ----                                ----------------                                                                                                                   
Script     5.3.4      AzureRM.profile                                                                                                                                                        
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...}                                                                    
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                                                                          
Script     1.1.7.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}                                                          
Script     1.6.0      PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}                                                              
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSReadlineKeyHandler...}                         

PS /Users/peter&gt; Connect-AzureRmAccount                                                                                                                                                       
Connect-AzureRmAccount : The term 'Connect-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Connect-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eefa9add-8626-ed24-7ab8-cf1fb07a3739
* Version Independent ID: 4baba292-2a6e-3a0f-a6bf-7e00356a95e8
* Content: [Install Azure PowerShell on macOS or Linux](https://docs.microsoft.com/en-us/powershell/azure/install-azurermps-maclinux?view=azurermps-6.6.0)
* Content Source: [docs-conceptual/azurermps-6.6.0/install-azurermps-maclinux.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.6.0/install-azurermps-maclinux.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Please include the following information:

* The platform running PowerShell
* The installed version of PowerShell
* The method by which the module was installed
* Whether `AzureRM.NetCore` or `AzureRM` was installed
* If running on a Unix system, if PowerShell was run with SUID root or superuser priviliges
* The output of `Get-Module -ListAvailable -Name AzureRM | Select-Object Name,Version` and `Get-Module -ListAvailable -Name AzureRM.NetCore | Select-Object Name,Version`

**Comment by sptramer** [comment]
@peterremote1980 - Please provide the requested information. Without additional information this issue will be closed on 10/12 as not actionable.

**Comment by sptramer** [comment]
Closing as inactionable. Also `AzureRM.Netcore` is now deprecated, in favor of `Az`.
