### ISSUE TITLE
How to Create a service principal just for PowerShell?

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-docs-powershell#681]
I want to create a service principal to login to Azure and do things.

I can logon using my Windows LIve ID, but that can't be automated. The solution is to create an SP, but this does not help me? What is 'demoapp' if all I want to do is use PowerShell for example to create a storage account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11cb61ed-1f1b-22ee-11a3-775bc9001538
* Version Independent ID: 84b2cbcb-1f11-9a6d-23fd-5c8d76453fa8
* Content: [Create an Azure service principal with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/create-azure-service-principal-azureps?view=azurermps-6.6.0#feedback)
* Content Source: [docs-conceptual/azurermps-6.6.0/create-azure-service-principal-azureps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.6.0/create-azure-service-principal-azureps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The identifier `demoapp` is a placeholder. Service Principals do not need to be tied to an application, but can be. If you look at the full documentation for [New-AzureRMADServicePrincipal](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/new-azurermadserviceprincipal?view=azurermps-6.6.0) you will see that the `-ApplicationId` parameter can be omitted.

In fact to create a generic service principal of the sort which may be best for scripting, including one with a randomized password generated for you, you can simply run the first example in the cmdlet documentation. https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/new-azurermadserviceprincipal?view=azurermps-6.6.0#examples
