### ISSUE TITLE
Running powershell script programatically from container

### ISSUE THREAD

**Issue by jdogg89** [Azure/azure-docs-powershell#692]
Is there a way to have powershell run programatically from a linux container? My use case is I want to schedule a container to run in my kubernetes cluster daily, and connect to azure to run a script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b619741-89c4-7375-f6a4-cf0cb00a790b
* Version Independent ID: 51584194-e101-e4d7-a033-fdf63e2d1d1e
* Content: [Run Azure PowerShell in a Docker container](https://docs.microsoft.com/en-us/powershell/azure/azurerm-ps-in-docker?view=azurermps-6.6.0)
* Content Source: [docs-conceptual/azurermps-6.6.0/azurerm-ps-in-docker.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.6.0/azurerm-ps-in-docker.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
You can get this behavior by using the `azuresdk/azure-powershell-core` container, which has the `pwsh` command installed on it. That command, and any stored scripts, can be invoked programmatically like any other local command via `docker exec`.

If you are building your own container, install PowerShell Core and then install the AzureRM.Core modules, as described in [Install Azure PowerShell on macOS or Linux](https://docs.microsoft.com/en-us/powershell/azure/install-azurermps-maclinux?view=azurermps-6.6.0).

**Comment by jdogg89** [comment]
unfortunately @sptramer this hasn't worked for me so far. I keep getting "Error: failed to start container "tagging": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/bin/pwsh\": stat /usr/bin/pwsh: no such file or directory", this is whether I give the full path in the CMD part of the dockerfile or if I just specify 'pwsh'. 

CMD [ "/usr/bin/pwsh" ]
or 
CMD [ "pwsh" ]

**Comment by sptramer** [comment]
This is a question that might be more appropriate for the engineering team, especially if there is not a way to invoke commands through `docker exec`. Please file an issue with them: https://github.com/Azure/azure-powershell/issues
