### ISSUE TITLE
Incorrect links for Import-AzureRmContext 

### ISSUE THREAD

**Issue by EdisonDa** [Azure/azure-docs-powershell#699]
1. Go to this page, https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azurermps-6.7.0
2. Click on "Import-AzureRmContext" link

We will get 404 page, here we should go to page /powershell/module/azurerm.profile/Import-AzureRmContext, not […]/Import-AzureRmAccount

**Comment by sptramer** [comment]
Has been fixed, but this issue wasn't tagged in the PR.
