### ISSUE TITLE
SEO rules - The article should have 2 or more H2 headings

### ISSUE THREAD

**Issue by EdisonDa** [Azure/azure-docs-powershell#701]
We have the SEO rule [**H2 Heading number**](https://review.docs.microsoft.com/en-us/csi/quality/content/docs-content-e2e/catstestcases/seo-rule/?branch=master#headings---h2-heading-number), however, here are two pages which have not followed the rule. 

* https://review.docs.microsoft.com/en-us/powershell/azure/manage-subscriptions-azureps?view=azurermps-6.7.0&branch=master
* https://review.docs.microsoft.com/en-us/powershell/azure/other-install?view=azurermps-6.7.0&branch=master

See QA report [here](https://contentqacats/CheckResults/2018081500004/Report/Failed/H2%20heading%20number)

**Comment by sptramer** [comment]
This is now part of a couple different tasks to be tracked separately since this issue indicates needed rewrites. Will leave the ticket open for now.

**Comment by sptramer** [comment]
Closing in favor of internal tracking since these are not user issues.
