### ISSUE TITLE
Need more Sample Scripts

### ISSUE THREAD

**Issue by msilinda** [Azure/azure-docs-powershell#717]
Need more Sample Scripts here beyond just IaaS, more around AAD, enterprise application configuration, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28323e6-8990-2a05-ca82-49dd2d1f5e98
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-6.8.1)
* Content Source: [docs-conceptual/azurermps-6.8.1/overview.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.8.1/overview.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@msilinda Without specific requests, this is not an actionable report. Please contact me internally if there are specific samples or information that somebody is looking for.
