### ISSUE TITLE
Powershell Core Install-Module AzureRM.NetCore silently dies

### ISSUE THREAD

**Issue by okaicomputer** [Azure/azure-docs-powershell#722]
OS:  Windows Subsystem for Linux, Debian 9
Powershell Core:  6.0.4
PowershellGet:  1.6.0

Issue:  When running Install-Module AzureRM.NetCore, the status of the module installation begins normally.  Immediately after Azure.Storage.Netcore is downloaded, the installation silently dies.

**Comment by sptramer** [comment]
Please file this issue with the engineering team:

https://github.com/azure/azure-powershell/issues
