### ISSUE TITLE
Uninstalling older versions

### ISSUE THREAD

**Issue by eschrader** [Azure/azure-docs-powershell#726]
To upgrade, I had to uninstall and install the new one.
Uninstall-Module AzureRM
Install-Module -Name AzureRM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bb841bc-9523-db0c-b2a7-64fc2f1c602d
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.8.1)
* Content Source: [docs-conceptual/azurermps-6.8.1/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.8.1/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by SeanLeavitt** [comment]
#List the versions of AzureRM on your machine:
Get-Module AzureRM -ListAvailable | Select-Object -Property Name, Version, Path

#Target a specific version of AzureRM to remove on your machine (when you have multiple).

<##Uninstall All Modules Example Function##>
function Uninstall-AllModules {
  param(
    [Parameter(Mandatory=$true)]
    [string]$TargetModule,
    [Parameter(Mandatory=$true)]
    [string]$Version,
    [switch]$Force
  )

  $AllModules = @()

  'Creating list of dependencies...'
  $target = Find-Module $TargetModule -RequiredVersion $version
  $target.Dependencies | ForEach-Object {
    $AllModules += New-Object -TypeName psobject -Property @{name=$_.name; version=$_.requiredversion}
  }
  $AllModules += New-Object -TypeName psobject -Property @{name=$TargetModule; version=$Version}

  foreach ($module in $AllModules) {
    Write-Host ('Uninstalling {0} version {1}' -f $module.name,$module.version)
    try {
      Uninstall-Module -Name $module.name -RequiredVersion $module.version -Force:$Force -ErrorAction Stop
    } catch {
      Write-Host ("`t" + $_.Exception.Message)
    }
  }
}
<##END EXAMPLE FUNCTION##>

##Example usages to remove a specific version of AzureRM on your machine (based on function above).
#Uninstall-AllModules -TargetModule AzureRM -Version 5.7.0 -Force
#Uninstall-AllModules -TargetModule AzureRM -Version 6.2.1 -Force

**Comment by sptramer** [comment]
For instructions on uninstalling, please see the [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-azurerm-ps) article.
