### ISSUE TITLE
Set-AzureRmRoleDefinition goes to 404 page

### ISSUE THREAD

**Issue by EdisonDa** [Azure/azure-docs-powershell#728]
1. Goes to https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azurermps-6.8.1
2. Click Set-AzureRmRoleDefinition
3. It goes to https://docs.microsoft.com/en-us/powershell/moduel/AzureRM.Resources/Set-AzureRmRoleDefinition, which is a 404 page

**Comment by MiYanni** [comment]
@EdisonDa The word `module` is spelled wrong in the link. Made a PR for it.

**Comment by sptramer** [comment]
@EdisonDa @MiYanni This will have to be fixed in the source the reference docs are generated from, or it will reappear with new releases. Make a PR against http://github.com/azure/azure-powershell

**Comment by MiYanni** [comment]
@sptramer That is incorrect. We (azure-powershell) do not maintain conceptual documentation. The edit button on the page goes to the correct repo. I've already created a PR there.

**Comment by sptramer** [comment]
My bad; I read the original post title and skimmed the links. I didn't notice that it was for conceptual documentation. Mea culpa.
