### ISSUE TITLE
Import-Module AzureRM.NetCore should be replaced?

### ISSUE THREAD

**Issue by sdavis3** [Azure/azure-docs-powershell#732]
It appears Import-Module AzureRM.NetCore and Connect-AzureRmAccount don't work after spining up a container. The Docker Hub repo for the container indicates the command to connect to an Azure account is Add-AzureRmAccount, which does successfully work. 

Alternatively, perhaps the documentation should read "Install-Module AzureRM.NetCore" and not "Import-Module AzureRM.NetCore".

Am I missing somthing?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d93f3194-ff59-02b1-8e3a-22a5647fe107
* Version Independent ID: 51584194-e101-e4d7-a033-fdf63e2d1d1e
* Content: [Run Azure PowerShell in a Docker container](https://docs.microsoft.com/en-us/powershell/azure/azurerm-ps-in-docker?view=azurermps-6.8.1)
* Content Source: [docs-conceptual/azurermps-6.8.1/azurerm-ps-in-docker.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.8.1/azurerm-ps-in-docker.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Can you tell me which container you're trying to run? It may not have AzureRM.NetCore installed.

**Comment by sdavis3** [comment]
docker run -it azuresdk/azure-powershell-core:latest

**Comment by sdavis3** [comment]
Issuing an "Install-Module" command does work...that differs from what the doc indicates.

**Comment by sptramer** [comment]
References to `AzureRM.Netcore` have been removed and an issue has been filed to add the `Connect-AzureRmAccount` cmdlet to `Az`. Going to close this issue.
