### ISSUE TITLE
Get-AzureRMAD* cmdlets don't support same parameters as Get-AzureAD*

### ISSUE THREAD

**Issue by ChristopherGLewis** [Azure/azure-docs-powershell#735]
Why don't the Get-AzureAMAD* (get-azurermaduser et al.) commands don't support the same parameters as the Get-AzureAD* commands?

I'm specifically trying to port a -Filter parameter (Specifies an oData v3.0 filter statement) and am surprised this functionality didn't get ported.

The basic search functionality offered in Get-AzureRMAD* is pretty slim.

**Comment by sptramer** [comment]
Please file product issues with the engineering team: https://github.com/azure/azure-powershell/issues
