### ISSUE TITLE
App Service - Web Site Netframeworkversion property inaccurately reported

### ISSUE THREAD

**Issue by jrgithub** [Azure/azure-docs-powershell#742]
Hi,

One issue and one question:

Issue: When running the following the netFrameworkVersion property is being reported as v4.0 (also appears inaccurate when browsing via Resource Explorer so assuming Powershell is relying on the same) even though it is set properly to a higher version on the Azure Portal (Powershell script and output below where the version on Azure Portal has been set via App Service - Application Settings - to v4.7)

$websiteProps = (Get-AzureRmResource -ResourceGroupName 01resgrp -ResourceType Microsoft.Web/sites/config -ResourceName $website.Name -ApiVersion 2018-02-01)

$websiteProps.Properties.NetFrameworkVersion 

netFrameworkVersion              : v4.0

Question: Where and how can one set the netFrameworkVersion property for Azure Functions via the Azure Portal? The menu option does not appear under Application Settings.

**Comment by sptramer** [comment]
@jrgithub - This sounds like you're experiencing several issues which aren't related to the documentation. If you have a problem with the Azure PowerShell tool itself, please file an issue with the engineering team: https://github.com/azure/azure-powershell/issues

If you're experiencing problems with Functions or the Portal, you will need to report an issue to that team. Portal issues can be reported through the "Report a Bug" button on the Portal. Functions has a README describing how to get help or file a report: https://github.com/Azure/Azure-Functions
