### ISSUE TITLE
New-AzureRmOperationalInsightsWorkspace Wrong -SKU

### ISSUE THREAD

**Issue by PawelLiebich** [Azure/azure-docs-powershell#748]
Hi Team,
The documentation and the cmdlet have a problem with -SKU for Log Analytics. I can not create LAs with PowerShell. In old LA I have the "pergb2018" option, but it does not work when creating a new one.

Module:AzureRM.OperationalInsights

PS C:\dev\> **New-AzureRmOperationalInsightsWorkspace -Location $Location -Name $WorkspaceName -Sku premium -ResourceGroupName $ResourceGroup**
New-AzureRmOperationalInsightsWorkspace : HTTP Status Code: BadRequest
Error Message: Pricing tier doesn't match the subscription's billing model. Read http://aka.ms/PricingTierWarning for more details.

PS C:\dev\> **New-AzureRmOperationalInsightsWorkspace -Location $Location -Name $WorkspaceName -Sku pergb2018 -ResourceGroupName $ResourceGroup**
New-AzureRmOperationalInsightsWorkspace : Cannot validate argument on parameter 'Sku'. The argument "pergb2018" does not belong to the set "**free,standard,premium,pernode,standalone**" specified by the ValidateSet attribute.
Supply an argument that is in the set and then try the command again.

**Comment by sptramer** [comment]
@PawelLiebich - This looks like an engineering issue or reference documentation problem. Those issues are handled by the engineering team. Please file a ticket at https://github.com/azure/azure-powershell/issues
