### ISSUE TITLE
Get Correlation Id for any operation

### ISSUE THREAD

**Issue by SharmainePopov** [Azure/azure-docs-powershell#753]
Hi, for  commands that cause an activity log entry to be created, I need to be able to pull the correlation id (s) of the operations somehow. For example update-azurermvm. I can't figure out how to the correlation id out without maybe parsing debug output

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0f67a2-1faa-949d-a071-8d238e201252
* Version Independent ID: 1068f896-b7a8-de23-ebe6-c03aad0398c9
* Content: [Overview of Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-6.9.0)
* Content Source: [docs-conceptual/azurermps-6.9.0/overview.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.9.0/overview.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@SharmainePopov Can you please provide an example of how you're running the command, and what information you expect to get out of it? If it's information which only appears in debug output, you will need to parse it.

**Comment by SharmainePopov** [comment]
It does only appear in debug output. This is as the customer puts it, cumbersome.

Here is the original message from my customer.

[cid:image001.png@01D467B9.02096D90]
[cid:image002.png@01D467B9.02096D90]
[cid:image003.png@01D467B9.02096D90]

Sharmaine Popov
Cloud Solution Architect |Microsoft Canada Inc. | sharmaine.popov@microsoft.com<mailto:sharmaine.popov@microsoft.com> | 416-799-0807

**Comment by sptramer** [comment]
@SharmainePopov Without further information this ticket will be closed on 2018-11-12.
