### ISSUE TITLE
The command Get-AzureRmVmDiskEncryptionStatus has a spelling mistake?

### ISSUE THREAD

**Issue by StefH** [Azure/azure-docs-powershell#754]
When running this command like:
```
Get-AzureRmVmDiskEncryptionStatus -ResourceGroupName $ResourceGroupName -VMName $VMName
```

The output is:
```
OsVolumeEncrypted          : NotEncrypted
DataVolumesEncrypted       : NotEncrypted
OsVolumeEncryptionSettings :
ProgressMessage            : No Encryption extension or metada found on the VM
```

I guess the `ProgressMessage` should be "No Encryption extension or metada**ta** found on the VM" ?

**Comment by sptramer** [comment]
This is an internal issue with the product. Please file a bug with the engineering team: https://github.com/azure/azure-powershell/issues
