### ISSUE TITLE
Creating a Service Principle using PowerShell does not register the application under the "Enterprise applications" list

### ISSUE THREAD

**Issue by rmodayil** [Azure/azure-docs-powershell#760]
I have registered the application, generated the key and successfully created the SPN with the application ID. But going back to the portal we noticed it does not end up in the 'Enterprise applications' list, however I can see it when 'All applications' is selected. Is there any way of tagging in the cmdlets to include it as an enterprise application?.

**Comment by sptramer** [comment]
@rmodayil This could be a product bug. Please file an engineering issue: https://github.com/azure/azure-powershell/issues
