### ISSUE TITLE
HKLM:\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters

### ISSUE THREAD

**Issue by michel3182** [Azure/azure-docs-powershell#777]
connecter ma box Android ,WECHIP  ,V7 avec l'application KODI  avec l 'application NAS  Synology ,merci.....  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa6c7f7-a61f-5a06-b964-888ee03eb86b
* Version Independent ID: a166875b-49f9-ea6d-d7ad-123189ef7b5c
* Content: [Install and configure the Azure PowerShell Service Management module](https://docs.microsoft.com/en-us/powershell/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0)
* Content Source: [docs-conceptual/azuresmps-4.0.0/install-azure-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azuresmps-4.0.0/install-azure-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
Je feme le probleme, parce què manque d'information. S'il vous plaît, signaler un bogue d'éauipe d'ingénierie: https://github.com/azure/azure-cli/issues

Pardonez mes mauvais français!
