### ISSUE TITLE
Use HUMAN friendly dates in documentation ...

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-docs-powershell#783]
ALL of the docs are using dates of the form nn/nn/nnnn -- For example: 10/07/2018 -- Is it 10-Jul-2018 or 7-Oct-2018???   Who knows !??    Using dd-mmm-yyyy is the most HUMAN friendly way to display dates as there is simply no room for ambiguity !!

If the docs must use numeric dates, can we not standardize to something like: yyyy-mm-dd (classic sort order)?

I know, a small, trival point -- but it drives me crazy !!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a120452f-c653-a761-637b-6c968d43f6ce
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.11.0)
* Content Source: [docs-conceptual/azurermps-6.11.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.11.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The date format is MM/DD/YYYY, the standard for American English date formatting.

**Comment by bdcoder2** [comment]
Too bad -- dd-mmm-yyyy leaves zero ambiguity for all cultures.
