### ISSUE TITLE
Valid values for Connect-AzureRmAccount -Environment option?

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-docs-powershell#784]
Documentation states:
   "Option '-Environment' can let you authenticate for Azure China or Azure Germany."

Where do I find a list of values that the -Environment accepts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6885ca73-660e-666c-0bd1-1f69a3a949b9
* Version Independent ID: cc8aa9be-2707-4ef6-e4d9-35498b837289
* Content: [Get started with Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/get-started-azureps?view=azurermps-6.11.0)
* Content Source: [docs-conceptual/azurermps-6.11.0/get-started-azureps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.11.0/get-started-azureps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@bdcoder2 - See the [Sign in to Another Cloud](https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azurermps-6.11.0#sign-in-to-another-cloud) documentation. Taking a note that this information should be added to "getting started" as well, so long as the instructions to sign in to another cloud are there.

**Comment by bdcoder2** [comment]
30 or 40 years ago (yes, I have been around that long!), when a parameter was listed for a command -- the VALUES the parameter accepted were also listed in the documentation -- THAT is what I am finding is missing in most MS (powershell) docs.  For example:

[https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/connect-azurermaccount?view=azurermps-6.11.0#optional-parameters](https://docs.microsoft.com/en-us/powershell/module/azurerm.profile/connect-azurermaccount?view=azurermps-6.11.0#optional-parameters)

Look at the **-Environment** option -- accepts a "String" -- OK -- but what are the valid values?  The list of values accepted should be present in the documentation for the -Environment option at this point -- not in some article I have no knowledge about -- or the only way to find it is by posting something on GitHub.

Good grief - When did everyone forget how to write technical documentation?

**Comment by sptramer** [comment]
The available cloud environments actually change depending on a user tenant, if the local site is configured for on-premises through an administrator setting up additional environments, etc. There is not a possible way to provide a complete static list of the environments via help as a result, since they are dynamic.

You are still welcome to file a reference bug with the engineering team. https://github.com/azure/azure-powershell

**Comment by bdcoder2** [comment]
@sptramer - thanks for the explanation, but I clearly have some research to do as you may as well have answered in Klingon!  (For complete newbies/beginners like myself, terms such as "user tenant" and "configured for on-premises" carry little to no meaning as I simply have no reference or definitions for such terms.  I keep reading, I understand what you are TRYING to say -- some values can be dynamic, but there is always some source for a value.  Thanks again.
