### ISSUE TITLE
Missing functionality in New-AzureRmAdGroup

### ISSUE THREAD

**Issue by ravensorb** [Azure/azure-docs-powershell#792]
Is there missing functionality related to specifying the group type (is it security enabled)?

**Comment by sptramer** [comment]
This is actually unclear from the reference documentation, but roles are not managed directly through the `New-` commands in AAD. You might want to look at [New-AzsureRmRoleAssignment](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/New-AzureRmRoleAssignment?view=azurermps-6.11.0), but docs indicate this is only for service principals. This might be better asked as a support question, or an issue filed with the engineering product: https://github.com/azure/azure-powershell
