### ISSUE TITLE
Please include list of valid VALUES accepted by cmdlet options!!!

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-docs-powershell#799]
I want to use the "New-AzureRmDiskConfig" cmdlet to create a premium storage data disk.  One of the options is "-SkuName" -- but wait, what are the valid VALUES I can use for that option?  There is no list, so I hunt (for 3 hours) until I find an example that shows "Premium_LRS" is a value that was used in an example I by chance found -- where did the author find that value? -- who knows?

Good grief -- HOW in the world is any programmer (me) who has never seen or used the "New-AzureRmDiskConfig" cmdlet supposed to know the VALID VALUES that are available for options when they are NOT documented?   Is the new generation of programmers born with this knowledge?  40 years of witnessing the decline of documentation!

On to the next option -OsType -- again no list of valid values that are accepted by this option -- but again, I HAPPEN to find an example that shows "Windows".  But again, I have no idea of the valid values -- I just happen to find the magic value in another example; that my friends, is NOT documentation.

PLEASE, for the love of god (if not my own sanity) start including lists of values accepted by cmdlet options OR (at the very least) provide a link to another cmdlet that can produce a list of valid values.

**Comment by sptramer** [comment]
If you have issues with reference documentation, please file a request with the engineering team. They maintain all online and in-cmdlet reference. https://github.com/azure/azure-powershell/issues

**Comment by bdcoder2** [comment]
Done - [https://github.com/Azure/azure-powershell/issues/7756](https://github.com/Azure/azure-powershell/issues/7756)
