### ISSUE TITLE
Bug in Uninstall-AllModules

### ISSUE THREAD

**Issue by zhusulai** [Azure/azure-docs-powershell#812]
`$AllModules += New-Object -TypeName psobject -Property @{name = $_.name; version = $_.requiredversion}` no longer works. It should be `version = $_.MinimumVersion`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a4014b0-0c32-afcb-d28c-b00c57ba85bf
* Version Independent ID: 9a312576-d1c8-6a00-c1ff-b52677b16e17
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-azurerm-ps?view=azurermps-6.12.0)
* Content Source: [docs-conceptual/azurermps-6.12.0/uninstall-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.12.0/uninstall-azurerm-ps.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by dhasek00** [comment]
Just tried it. version = $_.MinimumVersion did not work for me, but version = $_.requiredversion did

**Comment by zhusulai** [comment]
I'm using pwsh. Perhaps it has something to do with the issue.
