### ISSUE TITLE
Issue with New-AzsSubscription.md

### ISSUE THREAD

**Issue by amalik99** [Azure/azure-docs-powershell#813]
https://github.com/Azure/azure-docs-powershell/blob/master/azurestackps-1.2.11/AzureRM.AzureStackAdmin/New-AzsSubscription.md

It does not work if the tenant user logged doesn't have/had an existing subscription in AzureStack already

**Comment by sptramer** [comment]
This is a product bug. Please file a report with engineering. https://github.com/azure/azure-powershell/issues
