### ISSUE TITLE
Find the Image version for a VM

### ISSUE THREAD

**Issue by Ayanmullick** [Azure/azure-docs-powershell#826]
`(Get-AzureRmVM -Name &lt;Name&gt;-ResourceGroupName &lt;ResourceGroup&gt;).StorageProfile.ImageReference.Version` only outputs 'latest' and not the actual version number. How could one get the actual Image version number for a VM thru PowerShell.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13df5622-1e23-c1ab-5793-130fb5acaac3
* Version Independent ID: 334ff617-a357-d6de-327e-49bc5ae36bc9
* Content: [Query output of Azure PowerShell cmdlets](https://docs.microsoft.com/en-us/powershell/azure/queries-azureps?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/queries-azureps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/queries-azureps.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
To get the OS version number, you can inspect the `sku` property rather than `version`. There doesn't appear to be a way to get an independent version image number.
