### ISSUE TITLE
RequiredVersion is null Uninstall-AllModules

### ISSUE THREAD

**Issue by hawkbox** [Azure/azure-docs-powershell#828]
I'm running into a problem removing versions, it just fails on a parameter and the option for removing all installed versions fails right up until it removed 6.9.0. (6.9.0 removed without apparent issue)

PS C:\Powershell> Get-Module -Name AzureRM -List | select Name,Version

Name Version

AzureRM 5.5.0
AzureRM 5.1.1
AzureRM 6.13.1

PS C:\Powershell>
PS C:\Powershell> Uninstall-AllModules -TargetModule AzureRM -Version 6.13.1 -Force
Creating list of dependencies...
Uninstalling AzureRM.Profile version
Cannot validate argument on parameter 'RequiredVersion'. The argument is null. Provide a valid value for the argument, and then try running the command again.

**Comment by sptramer** [comment]
There's now a pull request which addresses this issue for uninstalling AzureRM. Unfortunately, uninstalling preview releases of Az is significantly more complicated, and why this change was originally made. I'm working on a solution to the issue now.

**Comment by hawkbox** [comment]
I didn't realize those 3 versions were preview releases. I just run the update command.  Thanks for looking into it.

**Comment by sptramer** [comment]
All AzureRM releases are stable - the preview module is Az (currently in 0.x. versioning). You can see more about that new module at [Introducing the new Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azurermps-6.13.0). Uninstall instructions for Az should be up later today.

**Comment by sptramer** [comment]
Closed by #840 - uninstall Az is a separate issue.

**Comment by hawkbox** [comment]
So is this fixed?  The literal instructions to install Az require me to uninstall these.  If the uninstall fails how is it a separate issue?  I'm trying to uninstall AzureRM, it's very clear in the original post. I don't understand what Az has to do with it and your answer doesn't explain it.

**Comment by sptramer** [comment]
The instructions for `Az` were updated to make it a little clearer that AzureRM uninstall isn't required (but you can't enable aliases if AzureRM is installed.) The new instructions will publish today at 3PM. If you need to uninstall before then, you can go ahead and see the instructions on github:

https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/uninstall-azurerm-ps.md

Hopefully this helps.

**Comment by hawkbox** [comment]
Those are literally the instructions I was using trying to remove 5.1.1 and 5.5.0 and getting the error I posted.  Did something change in the script to address it?  I've ran into multiple issues trying to do key stores with older versions of AzureRM installed and can't seem to remove them.

**Comment by hawkbox** [comment]
The 6.13.1 removal in the post was just the most recent example in my window when I made this. I got the same error with all versions other than 6.9.0 that removed without issue.

**Comment by sptramer** [comment]
The new script uses `$_.requiredVersion` rather than `$_.minimumVersion`. The difference here might actually be because of the fact that `6.13.1` is a patch. Going to reopen this issue and update the script once I validate that it works correctly with `$_.minimumVersion`.

**Comment by hawkbox** [comment]
Thanks.  That would make sense, I wondered if a term had been changed somewhere.

**Comment by sptramer** [comment]
Closed by #842.
