### ISSUE TITLE
Wrong link for "Persist user credentials across PowerShell sessions."

### ISSUE THREAD

**Issue by stej** [Azure/azure-docs-powershell#829]
[Enter feedback here]

I'm currently on page "Install the Azure PowerShell 'Az' module".

When I follow "Persist user credentials across PowerShell sessions.", this is documentation using Azure/AzureRM module. 
As AZ and Azure/AzureRM don't work well together, the link looks quite useless.

Could you provide right link, please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03d5fafc-2cf8-9c41-1e89-568453f13ed6
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell 'Az' with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/install-az-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@stej - We are currently in the process of updating documentation for the Az module, which will be released onto the site when the module reaches 1.0. It is currently in pre-release at this time, so features may change or be different from AzureRM. However, the instructions for maintaining context should work for both modules as described. The only difference may be the location of the context file, which under Az is stored in `$HOME/.Azure` or `$env:USERPROFILE\.Azure`.
