### ISSUE TITLE
"Use for App service" in Application Gateway

### ISSUE THREAD

**Issue by adrinr** [Azure/azure-docs-powershell#830]
I'm trying to create my deployment scripts for application gateway and I'm missing a param in AzureRmApplicationGatewayBackendHttpSettings. While the option "Use for App service" is available from the portal, I cannot manage to get the same configuration only using Powershell. Did anybody face the same problem?

**Comment by sptramer** [comment]
@adrinr - If there is a missing option for a cmdlet, please file a bug report with the engineering team: https://github.com/azure/azure-powershell/issues
