### ISSUE TITLE
Connect-AzureRmAccount on Az

### ISSUE THREAD

**Issue by fl1bbl3** [Azure/azure-docs-powershell#852]
The documentation says that Connect-AzureRmAccount should be used to logon.  Previous issues suggest Login-AzureRmAccount may work, but this doesn't seem to be the case either.

fl1bbl3@limbo:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
fl1bbl3@limbo:~$ pwsh
PowerShell 6.1.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/pscore6-docs
Type 'help' to get help.

PS /home/fl1bbl3> Get-Module -All

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     6.1.1.0    Microsoft.PowerShell.Commands.Ut... {Add-Member, Add-Type, Compare-Object, ConvertTo-Html...}
Binary     2.0.0.0    Microsoft.PowerShell.PSReadLine2    {Get-PSReadLineOption, Set-PSReadLineOption, Set-PSReadLineKeyHandler, Get-PSReadLineKeyHandler...}
Script     0.0        Microsoft.PowerShell.Utility        ConvertFrom-SddlString
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler...}

PS /home/fl1bbl3> Import-Module Az
PS /home/fl1bbl3> Connect-AzureRmAccount
Connect-AzureRmAccount : The term 'Connect-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Connect-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Connect-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

PS /home/fl1bbl3> Get-Module -ListAvailable -Name AzureRM | Select-Object Name,Version
PS /home/fl1bbl3> Get-Module -ListAvailable -Name AzureRM.NetCore | Select-Object Name,Version
PS /home/fl1bbl3> Get-Module -ListAvailable -Name Az | Select-Object Name,Version
PS /home/fl1bbl3> Get-Module -Name Az

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.7.0      Az

PS /home/fl1bbl3> Login-AzureRmAccount
Login-AzureRmAccount : The term 'Login-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Login-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Login-AzureRmAccount:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

PS /home/fl1bbl3>

**Comment by fl1bbl3** [comment]
Forgot installation method of Az.  It was installed via PSGallery

PS /home/fl1bbl3> Get-InstalledModule -Name Az

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
0.7.0                Az                                  PSGallery            Azure Resource Manager Module. Cmdlets to manage resources in Azure.  This module is compatible with PowerShell and PowerShel...

**Comment by sptramer** [comment]
This could be an issue with the `Az` aliasing. Make sure that you've enabled aliases with `Enable-AzureRMAlias`, and if the comamnd still doesn't work, [file an issue with the Azure PowerShell team](https://github.com/azure/azure-powershell/issues). I've brought this issue up to them before and it was supposed to be fixed.

**Comment by fl1bbl3** [comment]
Had run it (Enable-AzureRmAlias) initially as root, but hadn't run it as my user account.  Sorry!
