### ISSUE TITLE
Security Implication

### ISSUE THREAD

**Issue by CoRequisITe** [Azure/azure-docs-powershell#861]
From a security point of view it is unexeptable that Azure PowerShell saves the logon context by default. 

I understand this might be convenient for some tasks or users but there are some caveats if you ask me:

For example if you enable MFA as an extra security measure to use for managing resources in a subscription of a tenant, the user is not asked to sign in again every time he/she opens a new PowerShell session since the context is already saved. If the machine of a user/admin in the meantime gets infected, the context can be used to do serious damage in that Azure tenant since the context is already there.

In another example someone could ask the help of a colleague or co-worker. That person signs in Azure Powershell on the same desktop of the user/admin he or she is helping and after the help is finished the PowerShell session is closed. However the context is not since the default behavior of Azure PowerShell is to remember the context. The owner of the desktop can now do everything in the Azure tenant that the user that was helping out have permissions to (impersonation). This could in theory leave a big mess and an unfollowable audit trace if a security breach happens.

I have seen both scenarios in the real world since most PowerShell users are not aware of this behaviour.

I think this behaviour could have a serious implication on the security of an Azure tenant / subscription and should be disabled by default to prevent users from doing things they are unaware of.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2961ab4e-0dde-2b85-b42e-d1e67e9c3238
* Version Independent ID: f641b6fa-c346-ad1d-65a6-793a4bedcbdf
* Content: [Persist user credentials across PowerShell sessions](https://docs.microsoft.com/en-us/powershell/azure/context-persistence?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/context-persistence.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/context-persistence.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
If you consider this a security risk and would like to see the behavior changed, please file an issue with engineering: https://github.com/azure/azure-powershell/issues
