### ISSUE TITLE
AzureRM documentation pages are now dead links

### ISSUE THREAD

**Issue by Rabbit994** [Azure/azure-docs-powershell#876]
I'm sure this is due to Az Module going 1.0 but it's really user unfriendly to just have a bunch of dead links with no redirect to proper location. Either send people to new Az documentation or display older version of documentation. 

Examples:
https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/invoke-azurermvmruncommand

And just about everything the robot found is dead as well:
![image](https://user-images.githubusercontent.com/12375329/50230107-023daa80-037a-11e9-823c-4239dee15d76.png)

**Comment by sptramer** [comment]
Thanks for the report, this is actively being worked on. AzureRM reference should be live within a few hours.
