### ISSUE TITLE
Release notes for 1.0.1?

### ISSUE THREAD

**Issue by Absoblogginlutely** [Azure/azure-docs-powershell#883]
I ran an update-module -name az this morning and I am now at version 1.0.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ddce69f-d1eb-b3a1-01e9-93afec7f0207
* Version Independent ID: 92f67fd1-c7b3-7afb-0009-9a2cc19187b8
* Content: [1.0.0 - December 2018](https://docs.microsoft.com/en-us/powershell/azure/release-notes-azureps?view=azps-1.0.0)
* Content Source: [docs-conceptual/azps-1.0.0/release-notes-azureps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.0.0/release-notes-azureps.md)
* GitHub Login: @huypub

**Comment by sptramer** [comment]
There are occasionally hotfix releases which do not get published release notes. 1.0.1 is one of them.
