### ISSUE TITLE
Connect-AzAccount : The requested name is valid, but no data of the requested type was found

### ISSUE THREAD

**Issue by kpatnayakuni** [Azure/azure-docs-powershell#886]
Hello Team,

I am using new Azure PowerShell module Az, and I am encountering the error below when I am trying to reconnect to Azure, reconnect as in Disconnect-AzAccount and then Connect-AzAccount

In PSCore
![azpserror01](https://user-images.githubusercontent.com/31788728/50504584-930c3880-0a94-11e9-8da2-5f35a996b2e0.jpg)

In PSCore Preview as well
![azpserror02](https://user-images.githubusercontent.com/31788728/50504593-a3241800-0a94-11e9-968d-ef6d62afa300.jpg)

Thank you.

**Comment by sptramer** [comment]
This looks like a software bug. Can you please file an issue with engineering? https://github.com/azure/azure-powershell/issues
