### ISSUE TITLE
Get-Module -Name Az -ListAvailable returns nothing?

### ISSUE THREAD

**Issue by theheatDK** [Azure/azure-docs-powershell#887]
Hi,
I have installed Az and imported the module.
Get-Module -Name Az -ListAvailable returns nothing. If I remove ListAvailable it lists the module.
The module is installed in PSModulePath (C:\Users\MyUserName\Documents\WindowsPowerShell\Modules.
I have tested on two Windows 10 installations and both with and without scope CurrentUser.
Any ideas?
Regards Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1899b023-94ff-d2cf-fd2c-4c9a6a548db2
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.0.0)
* Content Source: [docs-conceptual/azps-1.0.0/install-az-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.0.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This might have to do with scope or availability issues, or the fact that the Az module is a rollup containing no commands itself. Going to change the instructions to use `Get-InstalledModule` instead, which will always return the correct results.

**Comment by sptramer** [comment]
Fixed by #894
