### ISSUE TITLE
Confusing documentation for New-AzureRmResourceGroupDeployment cmdlet

### ISSUE THREAD

**Issue by markgossa** [Azure/azure-docs-powershell#889]
Hi,

The documentation for the New-AzureRmResourceGroupDeployment cmdlet __mode__ parameter is confusing. See [here](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/new-azurermresourcegroupdeployment?view=azurermps-6.13.0) 

It's confusing because the definition for complete and incremental are on the same line as incremental. 

Thanks.

Mark

**Comment by sptramer** [comment]
Cmdlet documentation issues are handled by the engineering team. Please submit an issue or pull request with them: https://github.com/azure/azure-powershell
