### ISSUE TITLE
Naming related update

### ISSUE THREAD

**Issue by sethuramcbe** [Azure/azure-docs-powershell#892]
Will it not be better if the commands are named
New-VM rather than New-AzVm 

I believe New-VM,Get-VM is closer to english and easier than Adding AZ ,moreover the context is already withing Azure if we use this module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 163c6d47-15fc-5d82-0737-fcb564775a5a
* Version Independent ID: 524598ca-76aa-c8f5-cde1-d6bd626b757b
* Content: [Introducing the Azure PowerShell Az module](https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-1.0.0)
* Content Source: [docs-conceptual/azps-1.0.0/new-azureps-module-az.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.0.0/new-azureps-module-az.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
This was a decision made by engineering. If you would like to make this feature suggestion to them or get more information about why cmdlets are named this way, please file an issue with them: https://github.com/azure/azure-powershell/issues
