### ISSUE TITLE
Stop-AzureRmVM Id parameter documentaion

### ISSUE THREAD

**Issue by StefanSchoof** [Azure/azure-docs-powershell#893]
At https://github.com/Azure/azure-docs-powershell/blob/master/azurermps-6.13.0/AzureRM.Compute/Stop-AzureRmVM.md the Parameter `-Id` is documented with:
```
The resource group name
```
Since there is an parameter `-ResourceGroupName` this sound wrong.

**Comment by sptramer** [comment]
Please file an issue with the engineering team: They handle all cmdlet documentation: https://github.com/azure/azure-powershell/issues
