### ISSUE TITLE
wrong command provided

### ISSUE THREAD

**Issue by marrik96** [Azure/azure-docs-powershell#897]
The command uninstall-AzureRm appears to be incorrect.  What worked for me was "Uninstall-Module -Name AzureRM"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf3feb96-b9f9-c8a0-1ea9-ee52699fa445
* Version Independent ID: b3ce94fa-6e76-4ffe-e70e-07f7a321fcd4
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-az-ps?view=azps-1.0.0#uninstall-the-azurerm-module)
* Content Source: [docs-conceptual/azps-1.0.0/uninstall-az-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.0.0/uninstall-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
The command is valid, and part of the Az 1.0.0 release. See the [cmdlet documentation](https://docs.microsoft.com/en-us/powershell/module/Az.Accounts/Uninstall-AzureRm?view=azps-1.0.0).

**Comment by Absoblogginlutely** [comment]
I would agree with Marrik96 - uninstall-azurerm is only available with az module installed however installation guidelines such as https://docs.microsoft.com/en-us/powershell/azure/migrate-from-azurerm-to-az?view=azps-1.0.0 tell you to uninstall azurerm before installing az so the uninstall-azurerm commandlet will not be available to most users yet.

**Comment by Absoblogginlutely** [comment]
@sptramer can you reopen this please?

**Comment by sptramer** [comment]
AzureRM was never supported in PowerShell core. Users who never had AzureRM installed should know that they don't need to uninstall it. If the uninstall operation is not a no-op when AzureRM isn't installed on the system, that would be a product bug. Please file a request with engineering: https://github.com/azure/azure-powershell/issues

**Comment by ElectricLlama** [comment]
For me, right now, Uninstall-AzureRm results in this message: _WARNING: Both Az and AzureRM modules were detected on this machine. Az and AzureRM modules cannot be imported in the same 
session or used in the same script or runbook. If you are running PowerShell in an environment you control you can use the 
'Uninstall-AzureRm' cmdlet to remove all AzureRm modules from your machine. If you are running in Azure Automation, take 
care that none of your runbooks import both Az and AzureRM modules. More information can be found here: 
https://aka.ms/azps-migration-guide_ I've been trying to run COnnect-AzureAD for a few hours now. This is just like the good old days of "DLL hell". You've really messed this up
