### ISSUE TITLE
A Link to this Article Should be Posted on All Blog Announcements for New Az Module

### ISSUE THREAD

**Issue by PrometheusRising1** [Azure/azure-docs-powershell#904]
For all those using previous modules, after uninstalling those, you must use -AllowClobber as seen in the first sample code above.  This should be highlighted in all blog posts by Microsoft and on all articles.  Even those who understand -AllowClobber may forget to use it - this is a massive waste of time, as the module will not install properly if you leave it out.  If you doubt what I say Content Creators, just install AzureRM, AIP, Azure Storage Explorer, Az.Aks, then try uninstalling AzureRM and installing Az without -AllowClobber.  This will be a large number of users's experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1899b023-94ff-d2cf-fd2c-4c9a6a548db2
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-1.0.0)
* Content Source: [docs-conceptual/azps-1.0.0/install-az-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azps-1.0.0/install-az-ps.md)
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
I've made sure to relay this suggestion to our blog post writers. I don't know if they'll go back and edit older versions of the posts, but any new post will include a link to these install instructions.
