### ISSUE TITLE
Az module in Automation Account

### ISSUE THREAD

**Issue by hannwang1** [Azure/azure-docs-powershell#909]
What should I do with powershell module in Automation Account? Will Azure automatically update the module in Automation Account to Az OR I need to uninstall AzureRm and add Az,  or update AzureRm to Az.  How do I migrate my runbook from AzureRM to AZ

Can Azure please provide the instruction for Automation Account Runbook update to Az?

**Comment by georgewallace** [comment]
@hannwang1 At this time, the Az modules are not supported in Azure Automation as mentioned in this article [Azure PowerShell modules in Azure Automation](https://docs.microsoft.com/en-us/azure/automation/automation-update-azure-modules).  You should continue to use the AzureRM modules in your Automation Account.

**Comment by sptramer** [comment]
@hannwang1 I should also mention that when Az modules are supported, we'll be sure to message that out appropriately to Automation users.
